server:
  port: ${PORT:8100}

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://htriawujxrhtcu:e5818d61f975caf6ef4a070084318c37d66f320fe2530051bb9ebc1dbc890df7@ec2-52-30-159-47.eu-west-1.compute.amazonaws.com:5432/dcsfedjkbtmrav
    username: htriawujxrhtcu
    password: e5818d61f975caf6ef4a070084318c37d66f320fe2530051bb9ebc1dbc890df7
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: nd2k-registry-server.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/

security:
  allowedOrigins: https://svelte-gui.herokuapp.com/