server:
  port: 8100

spring:
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/