server:
  port: ${PORT}

spring:
  application:
    name: ${APP_NAME}
  h2:
    console:
      enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

security:
  allowedOrigins: http://127.0.0.1:5173
  access-token:
    public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
    private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  refresh-token:
    public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
    private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}